### ISSUE TITLE
problem magnet dynamics

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#121]
Current version i have (#79740dd5ba27ed72f566daf443ac8c56de7ed1e2) has the wrong FM precession frequency
Older version has the correct frequency ( #cb5a6a7de9caf4bbef4bd268cfa0725522b9ac45)
 i pulled from develop just now ( #dfb1268a6e5f6753ffe9278c10539af56fe48fa9 ) and it is still broken.

MWE:

precession radial frequency should be 6.49e11 Hz but it is 7.75e11. With 1muB it's a quasiperfect factor of 2 (2.2 vs 4.4)...

magnetic_init.dat:
`    0.951056516295154 0.0000000000000000E+00        0.309016994374947
`

input:
```
simulation magnet-dynamics 
H_ext 2.5 0.0 0.0

atomtypes 2
Fe  3.0 0.0 0.0 F #mu_s in mu_B, z*, m, phonons T/F
Ir  0.0 0.0 0.0 F

atoms 2
Fe 0.0  0.0   0.0 #element, x y z in lattice vectors
Ir 0.5 0.5 -0.7

#writting deleting
CalTheta .F.
Energy_Distrib .F.
gra_fft .F.
gra_log .T.
gra_Beff .F.
gra_freq 3000
Efreq 3000

gra_topo .F.
print_Econt T
energy_detail T
min_Efreq 100

# parameters of the lattice
Periodic_log .T. .T. .F.
Nsize 1 1 1
alat 1.0 1.0 1.0
lattice
0.5 -0.86602540378 0.0
0.5 0.86602540378 0.0
0.0 0.0 1.0


#input for the dynamic
integration 2  (1: simple integration 2:Heun  3: SIB ) 
timestep 1 (fs)
duration 300000
damping 0.01



```

**Comment by bertdupe** [comment]
the typo in the solver is corrected
