### ISSUE TITLE
spindyn issue

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#130]
current version (#3a23fa13d8feff77d16526dbcf034706cc569ee2) on develop breaks down for input below.  Not sure where this happened, commit #cb5a6a7de9caf4bbef4bd268cfa0725522b9ac45 works with the same input.  lowering timestep to 0.1 looks better but wrong dynamics. i have to use new version for file shape excitation. 

```

simulation  magnet-dynamics  
convergence_criteria 5.0d-11
H_ext 0.0 0.0 2.5
E_ext 0.0 0.0 0.0 # V/nm
enable_zeeman T

magnetic_J
1 1 1 3.68d-3     #between atoms 1 and 1, shell 1, amplitude in eV

magnetic_anisotropy
1  0.0  0.0 1.0 -0.7d-3 #atom type 1, eanx,eany,eanz in eV

magnetic_D #between atoms 1 and 1, mediated by 2, shell 1, amplitude in eV
1 1 2 1 1.39d-3

atomtypes 2
Fe  3.0 0.0 0.0 F #mu_s in mu_B, z*, m, phonons T/F
Ir  0.0 0.0 0.0 F

atoms 2
Fe 0.0  0.0   0.0 #element, x y z in lattice vectors
Ir 0.5 0.5 -0.7

#writting deleting
CalTheta .F.
Energy_Distrib .F.
gra_fft .F.
gra_log .T.
gra_Beff .F.
gra_freq 21666
Efreq 21666
gra_topo .F.
print_Econt T
energy_detail T
min_Efreq 100

# parameters of the lattice
Periodic_log .T. .T. .F.
Nsize 60 60 1
alat 1.0 1.0 1.0
lattice
0.5 -0.86602540378 0.0
0.5 0.86602540378 0.0
0.0 0.0 1.0


#input for the dynamic
integration 2  (1: simple integration 2:Heun  3: SIB ) 
timestep 1 (fs)
duration 866647
damping 0.01

#-------------- excitations
excitation_shape_r
shape1 plane

excitation_shape_t
 const_Bz  const    0.0  866647 3    0.0 0.0 2.5
  gauss_Bz  gauss    0.0 40.0  3   0.0 0.0 0.005  0.0  10.0
#wave EMwave  0.0   95930 3    0.0   0.0 0.005  1.0 1.0 9593     0.0  0.0  0.0 	 0.0 10000000.0 




excitations
Bfield const_Bz    shape1
Bfield gauss_Bz shape1

```

**Comment by loudesplat** [comment]
edit: so it seems lowering the timestep gives the correct dynamics again for a uniform excitation. But this should be able to run with 1fs timestep as it did before, it is very slow dynamics under a very weak excitation. With a more complex spatial profile of the excitation, even with a tiny amplitude the integration breaks down completely. 
 
same input file as above with this excitation: 

```
excitation_shape_r
shape plane
shape2 file

excitation_shape_t
 const_Bz  const    0.0 866647 3    0.0 0.0 2.5
 gauss_By  gauss    0.0 40.0  3   0.0 0.005 0.0  0.0  10.0


excitations
Bfield const_Bz    shape
Bfield  gauss_By shape2
```
and shape2_file: (i need the txt extension to upload to github)


[shape2_file.txt](https://github.com/bertdupe/Matjes/files/10085558/shape2_file.txt)

**Comment by bertdupe** [comment]
Hello,
I am looking at it now. You start from a skyrmion lattice magnetic texture?

**Comment by bertdupe** [comment]
first 
enable_zeeman T should be replaced by enable_H T
There was a problem with reading the position file as well.

**Comment by loudesplat** [comment]
init file: 
[magnetic_init.dat.txt](https://github.com/bertdupe/Matjes/files/10383597/magnetic_init.dat.txt)
(remove .txt extension)

**Comment by bertdupe** [comment]
send me the EM.dat file. I do not know what I should reproduce here.
