### ISSUE TITLE
energy_distrib missing for phonons

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#138]
when energy_distrib is called for the MD the energy comes out empty so im assuming it is not implemented for phonons.

**Comment by patrick432** [comment]
Hi Louise,
I guess you are using the molecular dynamics routine.
Having a glance at the code, it seems that in molecular_dynamics.f90 line 386 and 388 the 1 for magnetic sites as 4th argument of the write_energy_field call was not changed when copying the code from the magnetic dynamics.
Changing the 1 to 5 corresponding to atomic displacement (the numbers correspond to the order_parameter_name array in m_type_lattice) should fix this, although I probably never tested that.
Please try that and tell me the result.

In general I would change these magic numbers to some more readable parameters, but I don't have time for something like that.

**Comment by loudesplat** [comment]
Hi Patrick, thanks, i will try when i can but my point was that considering that as far as i can tell, energy distrib subroutine does not even use the order parameter number besides for fft hamiltonian,and at this point only the otder==1 case is implemented , I doubt this will do anything? But i also couldnt find the magic number for ph order parameter so that's good to know...

**Comment by loudesplat** [comment]
Alright it works for real space hamil, or at least it's printing something. Cheers!
