### ISSUE TITLE
error compiling Matjes-1.0

### ISSUE THREAD

**Issue by Soumeniisc** [bertdupe/Matjes#143]
Hi Bertdupe,

I am now trying to install the older stable version of the release Matjes-1.0. I was wondering which Fortran compiler you used to compile the code.  I am using **intel/parallel-studio-2020.4**. I am getting some errors while the Fortran code reads and writes into the file. Is there any flag to suppress the following IO error? I would appreciate any hunch or suggestion. 

**I am getting following trivial fortran IO error:** 

**1)**/home/skbag/Software/Matjes-1.0/src/excitations/excitation_io.f90(77): error #7421: A constant or general expression must appear in a format list in this context.   [/AI]
        write(output_unit,'(/AI3A/)') "Found ",nread," excitation entries which are read now"

**2)**/packages/apps/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort -DCPP_BLAS -DCPP_LAPACK -DCPP_MKL -DCPP_VERSIONGIT="\"''\"" -I/packages/apps/intel/compilers_and_libraries_2020.4.304/linux/mkl/include -fpp -free -O3 -fno-protect-parens -ffast-math -O3 -mkl=parallel -march=core-avx2  -free -c /home/skbag/Software/Matjes-1.0/src/tight-binding/types_tb_H_inp.f90 -o CMakeFiles/Matjes.dir/src/tight-binding/types_tb_H_inp.f90.o
ifort: command line warning #10006: ignoring unknown option '-ffast-math'
/home/skbag/Software/Matjes-1.0/src/tight-binding/types_tb_H_inp.f90(348): error #6358: Constants and expressions are invalid in read-only I/O lists.   [REAL]
        read(unit,*,iostat=iostat,iomsg=iomsg) tmp%attype, tmp%orbital ,tmp%dist, tmp%val%re, tmp%val%im
^
/home/skbag/Software/Matjes-1.0/src/tight-binding/types_tb_H_inp.f90(348): error #6358: Constants and expressions are invalid in read-only I/O lists.   [AIMAG]
        read(unit,*,iostat=iostat,iomsg=iomsg) tmp%attype, tmp%orbital ,tmp%dist, tmp%val%re, tmp%val%im

**My config.cmake**

message("reading config.cmake")

#one has to uncomment the linking languages in cmake/Files_and_Targets.cmake for ifort-.-

##stuff to load
#module purge
#module load Architecture/KNL
#module load GCC/8.3.0
#module load ParaStationMPI
#module load CMake/3.14.0
#module load imkl/2019.5.281
#module load Eigen

#module load cmake
#module load intel/parallel-studio-2020.4
set(CMAKE_Fortran_COMPILER ifort)
set(CMAKE_CXX_COMPILER icpc)

#manual adds to fortran compiler
set(compadd "-mkl=parallel -march=core-avx2")                                                   #add to release and debug
set(com_rel_add "")  #add to release
set(com_deb_add "")                                             #add to debug 

#set(add_lib ${add_lib} " -liomp5 -lpthread -lm -ldl")
#set(MKLROOT $ENV{MKLROOT})
#set(add_inc ${add_inc} "${MKLROOT}/include" )

#PREPROCESSOR FLAGS
#add_compile_definitions(CPP_MKL_SPBLAS)
#add_compile_definitions(CPP_BRUTDIP)
#set(Eigen3_DIR "/usr/local/software/jurecabooster/Stages/2019a/software/Eigen/3.3.7-GCCcore-8.3.0/share/eigen3/cmake/")

#add_compile_definitions(CPP_DEBUG)
#add_compile_definitions(CPP_DENSE_BLAS)
#add_compile_definitions(CPP_DENSE_BARE)

**Comment by Soumeniisc** [comment]
Now it is resolved with follwing GCC and mpi library combination
gcc-11.2.0-gcc-11.2.0 openmpi/4.1.5 cmake/3.27.7 fftw-3.3.10-gcc-12.1.0 eigen-3.4.0-gcc-11.2.0 gsl-2.7.1-gcc-12.1.0 netcdf-c-4.8.1-gcc-11.2.0 cuda-11.7.0-gcc-11.2.0 intel-mkl-2020.4.304-gcc-12.1.0

**Comment by bertdupe** [comment]
Congratulations!!!I am happy to hear this. Enjoy.Cheers,Bertrand Le 10.11.2023 à 20:52, Soumen ***@***.***> a écrit :﻿
Closed #143 as completed.
