### ISSUE TITLE
spin dynamics does not compile with intel fortran

### ISSUE THREAD

**Issue by bertdupe** [bertdupe/Matjes#63]
OS: Red Hat
1) os/el7   2) intel/18.0.2   3) mkl/18.0.2   4) impi/18.0.2   5) gcc/10.2.1   6) cmake/3.13.3   7) fftw/3.3.4
same with intel/21.2.0

No idea what is going on...

error message:
/tmp/ifortobP85a.i90: catastrophic error: Internal compiler error: segmentation violation signal raised Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /home/weil/soft/test/src/dynamics/spindynamics.f90 (code 1)
make[2]: *** [CMakeFiles/Matjes.dir/build.make:206: CMakeFiles/Matjes.dir/src/dynamics/spindynamics.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/Matjes.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by patrick432** [comment]
I managed to compile the code on ifort 19.1 with the above commit.
I hope it also works with your ifort version.
