### ISSUE TITLE
re:problem anisotropy_lat

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#65]
Continuing here since previous issue is closed.
The accuracy problem I get with anisotropy_lat and non cubic lattice vectors is as follows:

The input below,  and
```
magnetic_anisotropy
1  0.0  0.47 0.88 -1.0d-3 
```
indeed relaxes the mag along (0 0.47 0.88), whereas using

```
magnetic_anisotropy_lat
1  -0.47  0.47 0.88 -1.0d-3
```

relaxes along (0 0.52 0.85). I may be missing something but I think the 2 inputs should be equivalent. The inaccuracy with the _lat tag is very big.

```

#le chat mange la souris
simulation minimize_infdamp
convergence_criteria 1.0d-15

magnetic_J
1 1 1 10.0d-3    

#magnetic_anisotropy
#1  0.0  0.47 0.88 -1.0d-3 

magnetic_anisotropy_lat
1  -0.47  0.47 0.88 -1.0d-3

atomtypes 2
Fe  2.7 0.0 0.0 F #mu_s in mu_B, z*, m, phonons T/F
Ir  0.0 0.0 0.0 F

atoms 2
Fe 0.0  0.0   0.0 #element, x y z in lattice vectors
Ir 0.5 0.5 -0.7


# parameters of the lattice
Periodic_log .T. .T. .F.
Nsize 5 5 1
alat 1.0 1.0 1.0
lattice
0.707106781186547 -0.5 0.0
0.707106781186547 0.5 0.0
0.0 0.0 1.0
```

**Comment by bertdupe** [comment]
everything seems to work fine
the tag magnetic_anisotropy reads 3 reals and imposes the axis in the correct direction.
does the magnetic_anisotropy_lat reads 4 reals and convolute it with the lattice?

**Comment by bertdupe** [comment]
this works also with 2 anisotropy axes.
`magnetic_anisotropy
1 0.0 0.0 -1.0d-3
1 0.0 -1.0d-5 0.0`
