### ISSUE TITLE
segmentation fault  emerge when use a large Nsize

### ISSUE THREAD

**Issue by luowei1991** [bertdupe/Matjes#80]
Hi, Dr Dupe

I got a segmentation fault when I change the Nsize. It work for 4 4 1, but it fails for 8 8 1.
see the following:

_**_Heun integration method selected
Heun solver

 Butchers table
     0.00000     0.00000     0.00000
     1.00000     1.00000     0.00000
     1.00000     0.50000     0.50000

topological operators
duration: .36000E-04 seconds

done

Initial Total Energy (eV)  -0.438852919186E-001

Start excitation setup routine.

No excitations provided in input

No entry found for                  "update_time" in file "input", using default value:  F
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
Matjes-serial      0000000000646C9A  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B610943B630  Unknown               Unknown  Unknown
Matjes-serial      00000000006F4134  Unknown               Unknown  Unknown
Matjes-serial      0000000000414000  Unknown               Unknown  Unknown
Matjes-serial      0000000000410D03  Unknown               Unknown  Unknown
Matjes-serial      000000000040507B  Unknown               Unknown  Unknown
Matjes-serial      0000000000404B12  Unknown               Unknown  Unknown
libc-2.17.so       00002B6109F48555  __libc_start_main     Unknown  Unknown
Matjes-serial      0000000000404A29  Unknown               Unknown  Unknown_**_

Best regards,
Wei

**Comment by patrick432** [comment]
Dear Wei,

thanks for reporting this problem.
In general the code is able to consider cells much larger than 8 8 1 so I am quite curious why your case fails with increasing system size.

Unfortunately the provided output is not sufficient to fully understand the issue.
Can you provide a minimal example input causing this issue?
Alternatively, the output after compiling with debug options (enter "debug" after calling the compile.sh script) might be helpful.

Cheers,
Patrick

**Comment by bertdupe** [comment]
the problem was in the declaration of the declaration of Mout in the Euler solver.
It seems that some intel compiler do not understand the declaration Mout(Size(a)) in an interface. Instated one should use allocatable when the result of a function has a deferred size. The in the function one uses allocate(Mout(size(a))) and it works fine.
