### ISSUE TITLE
randist

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#87]
Trying to draw from normal distribution of std dev=1, apparently one has to use the randist module in /src/random-numbers. The comment l30 refers to this thesis p35 http://kops.uni-konstanz.de/bitstream/handle/123456789/9098/Diss_Schieback.pdf?sequence=1&isAllowed=y . l34 the factor used as the std dev seems to be sqrt(2*kT) where kT is the input parameter. So by calling randist(1.0d0), the distribution obtained has variance of ~sqrt(2)=1.4. Issues are the follwowing:

1)I do not know if this is on purpose and removing this factor of 2 might break the finite temperature magnetization dynamics.
2) When removing the 2, the new distribution indeed gets std dev of about 1 but looks really bad compared to e.g., what matlab prng does. See attached figures. 

I think I will switch to some external library for this, but this is an fyi because randist is used a lot in the code and actually takes input parameter of half the variance without it being specified anywhere as far as I can tell. 

![randist1](https://user-images.githubusercontent.com/37928020/150955672-a202137a-f4c6-416f-99e7-e7f0ff100157.png)
![randist2](https://user-images.githubusercontent.com/37928020/150955665-2e66a7bd-8beb-4972-8a21-407869805859.png)

**Comment by bertdupe** [comment]
chic random number did you take?

**Comment by bertdupe** [comment]
can you send your input please?

**Comment by bertdupe** [comment]
new random number generators have been included. I consider the problem as solved

**Comment by loudesplat** [comment]
I kept it open as a reminder than randist still takes half the variance as parameter and you meant to move it back into magnetization dynamics where it should probably be, otherwise yes I suppose this is solved (what I haven't solved is why Box Mueller always looks shit compared to whatever black magic matlab is doing to draw from normal distribution...I cannot reproduce the pretty distribution above even with mkl but it works either way so, eh)

**Comment by bertdupe** [comment]
the random number have been corrected.
There are 3 as described in the wiki
